### ISSUE TITLE
average_heat_loss_parameter in sap2012.SAP_worksheet.heat_losses_and_heat_loss_parameter

### ISSUE THREAD

**Issue by fourierfan** [building-energy/sap2012#1]
Currently: 
average_heat_loss_parameter = sum(heat_loss_parameter) / total_floor_area

Should be:
average_heat_loss_parameter = sum(heat_loss_parameter) / 12.0

**Comment by stevenkfirth** [comment]
Thank you for spotting this.

Now fixed and new version (0.0.1) released on PyPi. https://pypi.org/project/sap2012/

**Comment by fourierfan** [comment]
You're welcome and thank you for writing and sharing this awesome tool.
