### ISSUE TITLE
What version of (Rd)SAP is implemented?

### ISSUE THREAD

**Issue by devanubis** [building-energy/sap2012#2]
Hi, specifically which version of RdSAP does this implement? Is it the latest version  `9.94`? Or an earlier version of SAP2012?

Also, would you be able to do a release to `pypi` from your `master` branch for the changes made in 2023?

**Comment by stevenkfirth** [comment]
Thank you for your questions.

> Hi, specifically which version of RdSAP does this implement? Is it the latest version  9.94? Or an earlier version of SAP2012?
At present this is an implematation of SAP2012 version 9.92. There is some work in the repository on also implementing RdSAP, which would then be able to take a smaller set of inputs and use built-in inferences to create the full set of inputs needed for the SAP2012 calculation. This is based on RdSAP version 9.94 but the implemention of this RdSAP version has not been completed.

> Also, would you be able to do a release to pypi from your master branch for the changes made in 2023?
I think that these changes were around the work on RdSAP which was not completed. So I'm not planning to create a new release. Please do download directly from GitHub if needed and do let me know if I have this wrong.

I am now working on an implementation of SAP10 - the next version of SAP after SAP2012. SAP10 is now being used for new dwellings and will be replacing SAP2012 for existing dwellings and EPCs later this year. If you would like more information on this, please contact me via my email s.k.firth@lboro.ac.uk.

**Comment by devanubis** [comment]
Thanks for your response!

>  I think that these changes were around the work on RdSAP which was not completed. So I'm not planning to create a new release. Please do download directly from GitHub if needed and do let me know if I have this wrong.

Yes that appears to be the case. The RdSAP inputs are what we were most interested in, so for now I think we'll continue our work without a SAP integration.

If our needs change would you be open to pull requests to implement the RdSAP mappings?
